import type {
  Lead,
  Client,
  ContentItem,
  Campaign,
  RecruitingJob,
  FinancialRecord,
  KPIs,
} from "./types";

export const kpis: KPIs = {
  leadsMonth: 34,
  callsScheduled: 12,
  activeClients: 8,
  mrr: 14200,
  forecastRevenue: 18500,
  cac: 420,
  avgRoas: 3.8,
  pendingProduction: 14,
  reelsDelivered: 47,
  activeAds: 11,
};

export const leads: Lead[] = [
  {
    id: "l1",
    name: "Markus Bauer",
    company: "FitLife Wien",
    phone: "+43 699 1234567",
    email: "markus@fitlifewien.at",
    source: "instagram",
    status: "call_agendada",
    niche: "fitness",
    revenue: "€50k–100k",
    advertises: false,
    need: "leads",
    ticket: "€1.500",
    createdAt: "2026-05-10",
    lastContact: "2026-05-14",
    notes: "Quer escalar academia, nunca fez ads antes.",
    assignedTo: "Rayana",
  },
  {
    id: "l2",
    name: "Sarah Mayer",
    company: "Klinik Mayer",
    phone: "+43 664 9876543",
    email: "sarah@klinik-mayer.at",
    source: "indicacao",
    status: "proposta_enviada",
    niche: "saúde",
    revenue: "€200k+",
    advertises: true,
    need: "leads + branding",
    ticket: "€2.500",
    createdAt: "2026-05-08",
    lastContact: "2026-05-15",
    notes: "Indicação da FitLife. Quer rebranding + Meta Ads para pacientes.",
    assignedTo: "Rayana",
  },
  {
    id: "l3",
    name: "Thomas Gruber",
    company: "Bau Gruber GmbH",
    phone: "+43 676 5551234",
    email: "t.gruber@baugruber.at",
    source: "meta_ads",
    status: "qualificacao",
    niche: "construção",
    revenue: "€500k+",
    advertises: false,
    need: "recruiting",
    ticket: "€3.000",
    createdAt: "2026-05-12",
    lastContact: "2026-05-13",
    notes: "Precisa contratar 10 trabalhadores. Muito interessado em Recruiting Ads.",
    assignedTo: "Rayana",
  },
  {
    id: "l4",
    name: "Ana Costa",
    company: "Belleza Studio",
    phone: "+43 699 3334444",
    email: "ana@bellezastudio.at",
    source: "tiktok",
    status: "novo_lead",
    niche: "beleza",
    revenue: "€30k–50k",
    advertises: false,
    need: "social media",
    ticket: "€790",
    createdAt: "2026-05-16",
    lastContact: "2026-05-16",
    notes: "Viu reel no TikTok. Estúdio de beleza em crescimento.",
    assignedTo: "Rayana",
  },
  {
    id: "l5",
    name: "Klaus Hofmann",
    company: "Hofmann Immobilien",
    phone: "+43 650 7778888",
    email: "k.hofmann@immobilien.at",
    source: "networking",
    status: "negociacao",
    niche: "imobiliário",
    revenue: "€1M+",
    advertises: true,
    need: "leads",
    ticket: "€4.000",
    createdAt: "2026-05-05",
    lastContact: "2026-05-15",
    notes: "Evento de networking. Quer Meta Ads + Google Ads para leads imobiliários.",
    assignedTo: "Rayana",
  },
  {
    id: "l6",
    name: "Laura Schmid",
    company: "Pilates by Laura",
    phone: "+43 699 2223333",
    email: "laura@pilatesbylau.at",
    source: "instagram",
    status: "fechado",
    niche: "fitness",
    revenue: "€20k–50k",
    advertises: false,
    need: "social media + ads",
    ticket: "€1.200",
    createdAt: "2026-04-28",
    lastContact: "2026-05-10",
    notes: "Fechou Growth package. Inicio em Junho.",
    assignedTo: "Rayana",
  },
  {
    id: "l7",
    name: "Michael Berger",
    company: "Berger Logistics",
    phone: "+43 664 1112222",
    email: "m.berger@logistics.at",
    source: "site",
    status: "perdido",
    niche: "logística",
    revenue: "€2M+",
    advertises: true,
    need: "recruiting",
    ticket: "€5.000",
    createdAt: "2026-04-20",
    lastContact: "2026-05-01",
    notes: "Foi para concorrente. Preço foi o motivo.",
    assignedTo: "Rayana",
  },
];

export const clients: Client[] = [
  {
    id: "c1",
    company: "FitBody Vienna",
    owner: "Stefan Huber",
    phone: "+43 699 4445555",
    email: "stefan@fitbodyvie.at",
    city: "Wien",
    niche: "fitness",
    website: "fitbodyvie.at",
    instagram: "@fitbodyvie",
    tiktok: "@fitbodyvie",
    objective: "Aumentar membros da academia",
    icp: "Homens 25-45, renda média-alta, Wien",
    offer: "Planos de treino personalizados",
    pains: "Custo de aquisição alto, membros cancelando",
    differentials: "Equipamentos premium, personal trainers certificados",
    competitors: "Basic Fit, Holmes Place",
    services: ["social_media", "meta_ads"],
    monthlyFee: 1800,
    dueDate: 5,
    paymentStatus: "pago",
    startDate: "2026-02-01",
    status: "active",
  },
  {
    id: "c2",
    company: "Dr. Medica Clinic",
    owner: "Dr. Eva Richter",
    phone: "+43 664 6667777",
    email: "eva@medicaclinic.at",
    city: "Graz",
    niche: "saúde",
    website: "medicaclinic.at",
    instagram: "@medicaclinic",
    tiktok: "",
    objective: "Gerar consultas para clínica estética",
    icp: "Mulheres 30-55, alta renda, Graz",
    offer: "Tratamentos estéticos premium",
    pains: "Sazonalidade, dependência de indicações",
    differentials: "Médicos especializados, equipamentos modernos",
    competitors: "Clinique Austria, Aesthetica",
    services: ["meta_ads", "landing_page", "social_media"],
    monthlyFee: 2500,
    dueDate: 10,
    paymentStatus: "pago",
    startDate: "2026-01-15",
    status: "active",
  },
  {
    id: "c3",
    company: "TechStart GmbH",
    owner: "Jonas Weber",
    phone: "+43 676 8889999",
    email: "jonas@techstart.at",
    city: "Wien",
    niche: "tecnologia",
    website: "techstart.at",
    instagram: "@techstartau",
    tiktok: "@techstartau",
    objective: "Recrutar desenvolvedores sênior",
    icp: "Devs 28-40, experiência 5+ anos",
    offer: "Startup tech, equity + salário competitivo",
    pains: "Mercado de tech aquecido, difícil atrair talentos",
    differentials: "Cultura forte, produto inovador",
    competitors: "Google AT, SAP",
    services: ["recruiting_ads", "meta_ads"],
    monthlyFee: 3200,
    dueDate: 1,
    paymentStatus: "pendente",
    startDate: "2026-03-01",
    status: "active",
  },
  {
    id: "c4",
    company: "Bella Aesthetics",
    owner: "Maria Gonzalez",
    phone: "+43 699 0001111",
    email: "maria@bellaaest.at",
    city: "Salzburg",
    niche: "beleza",
    website: "bellaaest.at",
    instagram: "@bellaaest",
    tiktok: "@bellaaest",
    objective: "Aumentar agendamentos online",
    icp: "Mulheres 20-45, Salzburg e região",
    offer: "Tratamentos de beleza e bem-estar",
    pains: "Agenda não preenchida, sem sistema de follow-up",
    differentials: "Ambiente premium, resultados comprovados",
    competitors: "Salões locais",
    services: ["social_media", "meta_ads", "google_ads"],
    monthlyFee: 1500,
    dueDate: 15,
    paymentStatus: "atrasado",
    startDate: "2026-03-15",
    status: "active",
  },
];

export const contentItems: ContentItem[] = [
  {
    id: "ct1",
    clientId: "c1",
    clientName: "FitBody Vienna",
    title: "3 erros que te impedem de perder peso",
    type: "reel",
    status: "edicao",
    assignedTo: "Editor",
    deadline: "2026-05-18",
    platform: ["instagram", "tiktok"],
    notes: "Hook forte nos primeiros 2 segundos",
    createdAt: "2026-05-14",
  },
  {
    id: "ct2",
    clientId: "c2",
    clientName: "Dr. Medica Clinic",
    title: "Antes e depois tratamento botox",
    type: "carousel",
    status: "aprovado",
    assignedTo: "Designer",
    deadline: "2026-05-19",
    platform: ["instagram"],
    notes: "Usar fotos aprovadas pela cliente. Ocultar rosto.",
    createdAt: "2026-05-13",
  },
  {
    id: "ct3",
    clientId: "c1",
    clientName: "FitBody Vienna",
    title: "Tour pela academia",
    type: "reel",
    status: "roteiro",
    assignedTo: "Rayana",
    deadline: "2026-05-20",
    platform: ["instagram", "tiktok"],
    notes: "Mostrar equipamentos premium, área de cardio e pesos",
    createdAt: "2026-05-15",
  },
  {
    id: "ct4",
    clientId: "c4",
    clientName: "Bella Aesthetics",
    title: "Ritual de skincare diário",
    type: "reel",
    status: "ideia",
    assignedTo: "Copywriter",
    deadline: "2026-05-22",
    platform: ["instagram", "tiktok"],
    notes: "Tendência de skincare. Hook: 'Você está usando protetor solar certo?'",
    createdAt: "2026-05-16",
  },
  {
    id: "ct5",
    clientId: "c2",
    clientName: "Dr. Medica Clinic",
    title: "FAQ: O que é bioestimulador?",
    type: "post",
    status: "design",
    assignedTo: "Designer",
    deadline: "2026-05-17",
    platform: ["instagram"],
    notes: "Visual clean, paleta dourada e branca",
    createdAt: "2026-05-12",
  },
  {
    id: "ct6",
    clientId: "c1",
    clientName: "FitBody Vienna",
    title: "Depoimento Stefan - 3 meses de resultado",
    type: "reel",
    status: "postado",
    assignedTo: "Editor",
    deadline: "2026-05-14",
    platform: ["instagram", "tiktok"],
    notes: "Postado. 12k views em 24h.",
    createdAt: "2026-05-10",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "cam1",
    clientId: "c1",
    clientName: "FitBody Vienna",
    name: "Academia — Lead Gen Maio",
    objective: "leads",
    budget: 800,
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    status: "ativa",
    cpm: 12.4,
    ctr: 2.8,
    cpl: 18.5,
    roas: 0,
    frequency: 2.1,
    leads: 43,
    spend: 420,
  },
  {
    id: "cam2",
    clientId: "c2",
    clientName: "Dr. Medica Clinic",
    name: "Clínica — Botox Conversão",
    objective: "conversion",
    budget: 1200,
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    status: "ativa",
    cpm: 18.7,
    ctr: 3.2,
    cpl: 45.0,
    roas: 4.2,
    frequency: 1.8,
    leads: 27,
    spend: 680,
  },
  {
    id: "cam3",
    clientId: "c3",
    clientName: "TechStart GmbH",
    name: "Tech — Dev Sênior Recruiting",
    objective: "recruiting",
    budget: 2000,
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    status: "ativa",
    cpm: 22.1,
    ctr: 1.9,
    cpl: 35.0,
    roas: 0,
    frequency: 3.1,
    leads: 38,
    spend: 1100,
  },
  {
    id: "cam4",
    clientId: "c4",
    clientName: "Bella Aesthetics",
    name: "Bella — Awareness Salzburg",
    objective: "awareness",
    budget: 500,
    startDate: "2026-05-10",
    endDate: "2026-05-31",
    status: "ativa",
    cpm: 8.9,
    ctr: 1.4,
    cpl: 0,
    roas: 0,
    frequency: 2.5,
    leads: 0,
    spend: 210,
  },
];

export const recruitingJobs: RecruitingJob[] = [
  {
    id: "r1",
    clientId: "c3",
    clientName: "TechStart GmbH",
    position: "Desenvolvedor Full-Stack Sênior",
    location: "Wien (Hybrid)",
    briefingDate: "2026-05-01",
    status: "qualificacao",
    budget: 2000,
    leads: 38,
    qualified: 12,
    hired: 0,
    cpl: 35.0,
  },
  {
    id: "r2",
    clientId: "c1",
    clientName: "FitBody Vienna",
    position: "Personal Trainer",
    location: "Wien",
    briefingDate: "2026-04-15",
    status: "contratado",
    budget: 800,
    leads: 52,
    qualified: 18,
    hired: 3,
    cpl: 14.2,
  },
  {
    id: "r3",
    clientId: "c2",
    clientName: "Dr. Medica Clinic",
    position: "Enfermeira Especializada",
    location: "Graz",
    briefingDate: "2026-05-10",
    status: "meta_ads",
    budget: 1200,
    leads: 8,
    qualified: 2,
    hired: 0,
    cpl: 42.5,
  },
];

export const financialRecords: FinancialRecord[] = [
  {
    id: "f1",
    clientId: "c1",
    clientName: "FitBody Vienna",
    type: "receita",
    category: "mensalidade",
    amount: 1800,
    date: "2026-05-05",
    status: "pago",
    invoice: "INV-2026-041",
    notes: "",
  },
  {
    id: "f2",
    clientId: "c2",
    clientName: "Dr. Medica Clinic",
    type: "receita",
    category: "mensalidade",
    amount: 2500,
    date: "2026-05-10",
    status: "pago",
    invoice: "INV-2026-042",
    notes: "",
  },
  {
    id: "f3",
    clientId: "c3",
    clientName: "TechStart GmbH",
    type: "receita",
    category: "mensalidade",
    amount: 3200,
    date: "2026-05-01",
    status: "pendente",
    invoice: "INV-2026-043",
    notes: "Aguardando confirmação transferência",
  },
  {
    id: "f4",
    clientId: "c4",
    clientName: "Bella Aesthetics",
    type: "receita",
    category: "mensalidade",
    amount: 1500,
    date: "2026-05-15",
    status: "atrasado",
    invoice: "INV-2026-044",
    notes: "3 dias de atraso. Entrar em contato.",
  },
  {
    id: "f5",
    clientId: "",
    clientName: "BlackStrategie",
    type: "despesa",
    category: "software",
    amount: 89,
    date: "2026-05-01",
    status: "pago",
    invoice: "",
    notes: "Zapier + Notion + Meta Business",
  },
  {
    id: "f6",
    clientId: "",
    clientName: "BlackStrategie",
    type: "despesa",
    category: "freelancer",
    amount: 600,
    date: "2026-05-14",
    status: "pago",
    invoice: "",
    notes: "Editor de vídeo — Maio",
  },
];

export const mrrChartData = [
  { month: "Jan", mrr: 4800 },
  { month: "Fev", mrr: 6200 },
  { month: "Mar", mrr: 8900 },
  { month: "Abr", mrr: 11400 },
  { month: "Mai", mrr: 14200 },
];

export const leadsChartData = [
  { month: "Jan", leads: 8, fechados: 1 },
  { month: "Fev", leads: 14, fechados: 2 },
  { month: "Mar", leads: 22, fechados: 3 },
  { month: "Abr", leads: 28, fechados: 2 },
  { month: "Mai", leads: 34, fechados: 3 },
];
